CREATE TABLE IF NOT EXISTS STUDY_GROUP(
NAME TEXT,
AGE INTEGER,
BEST_SUBJECT TEXT,
WEAKEST_SUBJECT TEXT);

INSERT INTO STUDY_GROUP (NAME, AGE, BEST_SUBJECT, WEAKEST_SUBJECT) VALUES

('Ven', 12, 'Math', 'Art'),
('Ollie', 12, 'Math', 'Science'),
('Kiana', 12, 'Math', 'Art'),
('Kat', 13, 'Math', 'Science');

SELECT * FROM STUDY_GROUP;

SELECT * FROM STUDY_GROUP WHERE AGE = 12;

SELECT * FROM STUDY_GROUP WHERE BEST_SUBJECT = 'Math';